export const products = [
  {
    id: 1,
    name: 'AstraMark AI',
    category: 'AI',
    description: 'Revolutionary AI-powered digital marketing tool that automates campaign creation, analyzes market trends, and optimizes your marketing strategy with intelligent insights.',
    tags: ['AI', 'Marketing', 'Automation', 'Analytics'],
    webLink: '#',
    featured: true,
  },
  {
    id: 2,
    name: 'BlogCraft AI',
    category: 'AI',
    description: 'Advanced AI content generation platform that creates high-quality, SEO-optimized blog posts, articles, and content with natural language processing and creative writing capabilities.',
    tags: ['AI', 'Content', 'SEO', 'Writing'],
    webLink: '#',
    featured: true,
  },
  {
    id: 3,
    name: 'Evntiq',
    category: 'Apps',
    description: 'Comprehensive event management platform that simplifies planning, ticketing, attendee management, and real-time event analytics for seamless event experiences.',
    tags: ['Events', 'Management', 'Ticketing', 'Analytics'],
    webLink: '#',
    featured: true,
  },
  {
    id: 4,
    name: 'ReelFactory',
    category: 'AI',
    description: 'AI-driven video creation tool that transforms ideas into engaging short-form videos, reels, and social media content with automated editing and effects.',
    tags: ['AI', 'Video', 'Social Media', 'Editing'],
    playStoreLink: '#',
    webLink: '#',
    featured: true,
  },
];
